import type { Lesson } from "../types";

export const lesson: Lesson = {
  id: 10,
  title: "HITL Review Checklist",
  subtitle: "The governance gate before any test merges",
  icon: "✅",
  sections: [
    {
      heading: "Why a Checklist?",
      content: "AI-generated code passes syntax checks and even runs successfully — but it can still be wrong. A test that clicks buttons without asserting outcomes, or asserts the wrong thing, gives false confidence. This checklist is the quality gate.",
      callout: "This checklist applies to ALL test code entering the repo — whether hand-written, recorded, or Copilot-generated. No exceptions."
    },
    {
      heading: "The Review Checklist",
      content: "Run through these items before approving any test MR. Each item is a yes/no gate. Any 'No' requires a fix before merge.",
      table: {
        headers: ["#", "Check", "Why It Matters"],
        rows: [
          ["1", "Does each test map to an acceptance criterion?", "Untraceable tests become orphaned and unmaintainable"],
          ["2", "Does every user action have a corresponding assertion?", "Actions without assertions only prove 'no crash' — not correctness"],
          ["3", "Are all selectors using data-testid or getByRole?", "CSS selectors break on every UI refactor"],
          ["4", "Zero instances of waitForTimeout or sleep?", "Hardcoded waits are the #1 source of flaky tests"],
          ["5", "Does the test use realistic (not mocked) data for happy path?", "Mocked happy paths miss integration bugs"],
          ["6", "Are error/edge cases covered (empty state, 500, timeout)?", "Edge cases are where production bugs hide"],
          ["7", "Is test data independent (no shared state between tests)?", "Shared state creates hidden ordering dependencies"],
          ["8", "Does the test name describe the user scenario?", "test('test 1') tells reviewers nothing"],
          ["9", "No hardcoded URLs or environment-specific values?", "Tests must run against any environment via baseURL"],
          ["10", "No sensitive data (real passwords, PII, tokens)?", "Test code is committed to the repo and visible to anyone with repository access"],
        ]
      }
    },
    {
      heading: "Copilot-Specific Red Flags",
      content: "These are patterns that Copilot frequently generates that should be caught in review.",
      table: {
        headers: ["Red Flag", "What Copilot Did", "Correct Fix"],
        rows: [
          ["Assertion-free test", "Generated clicks with no expect()", "Add assertion per action"],
          ["Hardcoded wait", "Added page.waitForTimeout(3000)", "Remove — rely on auto-wait"],
          ["Hallucinated selector", "Used data-testid that doesn't exist", "Verify against actual HTML"],
          ["Wrong assertion target", "Asserts page title instead of error msg", "Match assertion to AC"],
          ["Shared state", "Test 2 depends on Test 1's data", "Add setup/teardown per test"],
          ["Magic strings", "Hardcoded 'localhost:3000' in goto()", "Use baseURL from config"],
        ]
      },
      warning: "The hallucinated selector is the most dangerous pattern. Copilot will confidently use a data-testid that doesn't exist in your HTML. The test fails with a timeout, and the error doesn't tell you the selector is wrong — only that the element wasn't found."
    }
  ],
  exercises: [
    {
      difficulty: 'beginner',
      title: "Review an AI-Generated Test Against the HITL Checklist",
      description: "This test was generated by Copilot. Review it against the 10-point checklist, identify the violations, and write the corrected version.",
      narration: "Start by reading the test top to bottom and checking each of the 10 checklist items one by one — don't try to spot everything at once. You'll notice the hardcoded URL ('http://localhost:5173') immediately fails item #9, and the absence of any expect() calls fails item #2 before you even get to the selectors. Pay close attention to the CSS selectors like '#shipping-name' and 'button.next-btn' — these fail item #3 because they'll break the moment someone renames a class or ID. Once you've listed every violation in the comment block, rewrite the test substituting data-testid selectors, a relative URL, and an assertion after each meaningful navigation step to confirm you actually landed where you expected.",
      starterCode: `// AI-GENERATED TEST (has HITL violations — find and fix them):
test('test checkout', async ({ page }) => {
  await page.goto('http://localhost:5173/checkout/shipping');
  await page.locator('#shipping-name').fill('John');
  await page.locator('#shipping-address').fill('123 Main St');
  await page.locator('#shipping-city').fill('Springfield');
  await page.waitForTimeout(2000);
  await page.locator('button.next-btn').click();
  await page.locator('#card-number').fill('4111111111111111');
  await page.locator('button.next-btn').click();
});

// VIOLATIONS FOUND: [TODO — list checklist items that fail]
// CORRECTED TEST: [TODO — rewrite with fixes]`,
      solutionCode: `// VIOLATIONS FOUND:
// #2 - No assertions after any action
// #3 - Using CSS selectors (#shipping-name, button.next-btn)
//      instead of data-testid
// #4 - Uses waitForTimeout(2000) — hardcoded wait
// #8 - Generic test name "test checkout"
// #9 - Hardcoded URL "http://localhost:5173"
// #10 - Real-looking credit card number in test data

// CORRECTED TEST:
test('checkout flow completes shipping and payment steps', async ({ page }) => {
  await page.goto('/checkout/shipping');
  await expect(page.locator('[data-testid="shipping-heading"]')).toBeVisible();

  await page.locator('[data-testid="shipping-name"]').fill('Test User');
  await page.locator('[data-testid="shipping-address"]').fill('123 Test St');
  await page.locator('[data-testid="shipping-city"]').fill('Testville');
  await page.locator('[data-testid="next-button"]').click();

  await expect(page.locator('[data-testid="payment-heading"]')).toBeVisible();
  await page.locator('[data-testid="card-number"]').fill('4000000000000000');
  await page.locator('[data-testid="next-button"]').click();

  await expect(page.locator('[data-testid="review-heading"]')).toBeVisible();
});`,
      hints: [
        "Check each of the 10 items in the table above — the test violates at least 5",
        "Look for: missing assertions, CSS selectors, hardcoded waits, vague test name, hardcoded URLs",
        "The credit card number looks real — use an obvious test number instead",
      ],
    },
    {
      difficulty: 'intermediate',
      title: 'Find Bugs in the Admin Page',
      description: 'The Admin page has intentional bugs. Write tests that expose them. Bug 1: The seed data contains a duplicate email. Bug 2: Bulk deactivation shows stale status.',
      narration: "For each bug you're essentially writing a test that you expect to pass only because the bug exists — think of it as documenting the defect in code. Start the duplicate-email bug by typing 'alice' into the admin-search-input and then counting the resulting rows with .count(); if the count comes back greater than 1, you've proven the bug without needing to read individual cells. For the stale-status bug, check both checkboxes using their admin-bulk-checkbox-{n} testids, trigger the bulk action, and then immediately read the admin-user-status-{n} text content — you're asserting what the UI actually shows right now, not what it should show, which is what makes this a defect-documenting test rather than a passing one.",
      starterCode: `import { test, expect } from '@playwright/test';

test.describe('Admin Page Bug Discovery', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/login');
    await page.getByTestId('email-input').fill('admin@test.com');
    await page.getByTestId('password-input').fill('AdminPass1!');
    await page.getByTestId('login-button').click();
    await page.waitForURL('/dashboard');
    await page.goto('/admin');
    // Reset to clean state
    await page.getByTestId('admin-seed-reset').click();
  });

  test('BUG: seed data has duplicate email', async ({ page }) => {
    // TODO: Search for "alice" in the admin search
    // TODO: Count how many rows match
    // TODO: Collect all emails from matching rows
    // TODO: Assert that there ARE duplicates (this is the bug!)
    // HINT: In a real app, this should fail — duplicates shouldn't exist
  });

  test('BUG: bulk deactivate shows stale status', async ({ page }) => {
    // TODO: Select two users using their bulk checkboxes
    // TODO: Click the bulk action button to deactivate
    // TODO: Read the status cells of the deactivated users
    // TODO: Assert whether the status updated immediately
    // HINT: The bug is that status doesn't update until page refresh
  });
});`,
      solutionCode: `import { test, expect } from '@playwright/test';

test.describe('Admin Page Bug Discovery', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/login');
    await page.getByTestId('email-input').fill('admin@test.com');
    await page.getByTestId('password-input').fill('AdminPass1!');
    await page.getByTestId('login-button').click();
    await page.waitForURL('/dashboard');
    await page.goto('/admin');
    await page.getByTestId('admin-seed-reset').click();
  });

  test('BUG: seed data has duplicate email', async ({ page }) => {
    await page.getByTestId('admin-search-input').fill('alice');
    const rows = page.locator('[data-testid^="admin-user-row-"]');
    const count = await rows.count();
    // BUG: Alice appears twice with the same email
    // In a correct system, this test should find exactly 1 row
    expect(count).toBeGreaterThan(1); // This passes — proving the bug
  });

  test('BUG: bulk deactivate shows stale status', async ({ page }) => {
    // Select first two users
    await page.getByTestId('admin-bulk-checkbox-1').check();
    await page.getByTestId('admin-bulk-checkbox-2').check();
    await page.getByTestId('admin-bulk-action').click();

    // BUG: Status cells still show "Active" immediately after deactivation
    // The UI doesn't re-render until page refresh
    const status1 = await page.getByTestId('admin-user-status-1').textContent();
    const status2 = await page.getByTestId('admin-user-status-2').textContent();

    // This assertion documents the bug — status should say "Inactive"
    // but the stale state bug means it still says "Active"
    // In a fixed app: await expect(page.getByTestId('admin-user-status-1')).toHaveText('Inactive');
    console.log('Status after deactivate:', status1, status2);
  });
});`,
      hints: [
        'Use admin-search-input to search for "alice" and count matching rows',
        'Bulk checkboxes use testid pattern: admin-bulk-checkbox-{userId}',
        'After bulk deactivation, check admin-user-status-{userId} for the expected value',
        'The stale state bug means status won\'t update — document this as a found defect',
      ],
    },
    {
      difficulty: 'advanced',
      title: 'HITL Review: Admin Invite and Search',
      description: 'Write a test for the admin invite flow and search functionality, then review your own test against the HITL checklist. Identify and fix any violations before submitting.',
      narration: "Write the test in a natural first pass — login, navigate, fill the invite form with admin-invite-name, admin-invite-email, and admin-invite-role, submit, then search — and only then put on your reviewer hat. Go through each of the six checklist items in the comment scaffold and honestly mark every one pass or fail against your own code, because the skill here is catching your own blind spots before formal review. Notice that after every navigation or form submission there should be an assertion confirming the expected state, not just the next action; an assertion like expect(rows.first()).toContainText('Test User') after the search is what separates a test that verifies behavior from one that just runs through the motions.",
      starterCode: `import { test, expect } from '@playwright/test';

// Write a test that:
// 1. Logs in as admin
// 2. Navigates to /admin
// 3. Fills the invite form (name, email, role)
// 4. Submits the invite
// 5. Searches for the newly invited user
// 6. Asserts they appear in the table
//
// THEN: Review your test against these HITL checklist items:
// [ ] Every action has an assertion
// [ ] Uses data-testid selectors
// [ ] No waitForTimeout
// [ ] Descriptive test name
// [ ] No hardcoded URLs
// [ ] Test data doesn't look like real PII

test('TODO: write your test here', async ({ page }) => {

});

// HITL REVIEW NOTES:
// List any violations you found in your own test:
// 1.
// 2.`,
      solutionCode: `import { test, expect } from '@playwright/test';

test('admin can invite a new user and find them via search', async ({ page }) => {
  // Arrange — login as admin
  await page.goto('/login');
  await page.getByTestId('email-input').fill('admin@test.com');
  await page.getByTestId('password-input').fill('AdminPass1!');
  await page.getByTestId('login-button').click();
  await page.waitForURL('/dashboard');

  // Act — navigate and invite
  await page.goto('/admin');
  await page.getByTestId('admin-seed-reset').click(); // Clean state

  await page.getByTestId('admin-invite-name').fill('Test User');
  await page.getByTestId('admin-invite-email').fill('testuser@example.com');
  await page.getByTestId('admin-invite-role').selectOption('editor');
  await page.getByTestId('admin-invite-submit').click();

  // Assert — search for the new user
  await page.getByTestId('admin-search-input').fill('Test User');
  const rows = page.locator('[data-testid^="admin-user-row-"]');
  await expect(rows.first()).toBeVisible();
  await expect(rows.first()).toContainText('Test User');
  await expect(rows.first()).toContainText('testuser@example.com');
});

// HITL REVIEW NOTES:
// All items pass:
// [x] Every action has a follow-up assertion or leads to one
// [x] Uses data-testid selectors throughout
// [x] No waitForTimeout — uses auto-retrying assertions
// [x] Descriptive test name explains the user scenario
// [x] Uses relative URL /admin (baseURL handles host)
// [x] Test data (testuser@example.com) is clearly fake`,
      hints: [
        'Start by resetting seed data with admin-seed-reset to ensure clean state',
        'Fill the invite form: admin-invite-name, admin-invite-email, admin-invite-role',
        'After inviting, search for the user with admin-search-input',
        'Review your test against each HITL item before looking at the solution',
      ],
    },
  ],
  promptTemplates: [
    {
      label: "Review AI-Generated Test",
      context: "Paste a Copilot-generated test and ask for a HITL review against the checklist.",
      prompt: "Review this Playwright test against our HITL checklist. For each of these 10 items, mark PASS or FAIL:\n1. Maps to acceptance criterion?\n2. Every action has an assertion?\n3. Uses data-testid or getByRole selectors?\n4. Zero waitForTimeout calls?\n5. Realistic data for happy path?\n6. Edge cases covered?\n7. No shared state between tests?\n8. Descriptive test name?\n9. No hardcoded URLs?\n10. No sensitive data?\n\nTest code:\n[PASTE TEST HERE]\n\nFor each FAIL, explain the violation and show the fix.",
    },
    {
      label: "Fix HITL Violations",
      context: "After identifying violations, ask Copilot to fix them while preserving test intent.",
      prompt: "This test has the following HITL violations:\n[LIST VIOLATIONS]\n\nFix each violation while preserving the original test intent. Use data-testid selectors, remove hardcoded waits, add assertions after each meaningful action, and use a descriptive test name that explains the user scenario.",
    },
  ],
  quiz: {
    question: "A Copilot-generated test passes but has no expect() assertions. What should you do?",
    options: [
      "Approve it — if it passes, it works",
      "Add assertions that verify the acceptance criteria before approving",
      "Delete it and write the test manually",
      "Ask Copilot to add assertions automatically without reviewing them"
    ],
    correctIndex: 1,
    explanation: "A test without assertions only proves the app doesn't crash during the flow — not that it produces correct results. Add assertions that map to the ticket's acceptance criteria, then verify those assertions are checking the right things."
  },
  practiceLink: {
    url: "http://localhost:5173/settings",
    label: "Review the Settings page — its toggles and forms are ideal for practicing HITL test review",
    description: "The Settings page demonstrates complex UI elements that require careful assertion review",
  }
};
